import { cloneOrbitTrapAppearance } from '../visuals/traps/orbitMaterial';
import { cloneOrbitTrapSet, createOrbitTrap, MAX_ORBIT_TRAPS } from '../visuals/traps/orbitTraps';
import { getOrbitTrapAppearance, getOrbitTrapSet } from '../visuals/materials/runtime';
import type { MaterialDefinition } from '../visuals/materials/registry';
import type { OrbitTrapPaletteMapping, OrbitTrapShape, RenderConfig } from '../types/config';

interface MaterialControlsProps { definition: MaterialDefinition; config: RenderConfig; onChange: (updater: (current: RenderConfig) => RenderConfig) => void; }
const trapShapes: { id: OrbitTrapShape; label: string }[] = [{ id: 'point', label: 'Point' }, { id: 'line', label: 'Line' }, { id: 'circle', label: 'Circle' }, { id: 'cross', label: 'Cross' }, { id: 'spiral', label: 'Spiral' }];

export function ActiveMaterialControls({ definition, config, onChange }: MaterialControlsProps) {
  switch (definition.editorId) {
    case 'orbitTrap': return <OrbitTrapMaterialControls config={config} onChange={onChange} />;
    case 'topographic': return <TopographicMaterialControls config={config} onChange={onChange} />;
    case 'domainColouring': return <DomainMaterialControls config={config} onChange={onChange} />;
    case 'surface': return <SurfaceMaterialControls config={config} onChange={onChange} />;
    default: return <ClassicMaterialControls config={config} onChange={onChange} />;
  }
}

function ClassicMaterialControls({ config, onChange }: Omit<MaterialControlsProps, 'definition'>) { return <div className="control-panel__grid"><DensityControl config={config} onChange={onChange} /></div>; }
function OrbitTrapMaterialControls({ config, onChange }: Omit<MaterialControlsProps, 'definition'>) {
  const trapSet = getOrbitTrapSet(config); const appearance = getOrbitTrapAppearance(config);
  const updateTraps = (updater: (current: typeof trapSet) => typeof trapSet) => onChange((current) => ({ ...current, material: { ...current.material, orbitTraps: updater(getOrbitTrapSet(current)) } }));
  const updateAppearance = (updater: (current: typeof appearance) => typeof appearance) => onChange((current) => ({ ...current, material: { ...current.material, orbitAppearance: updater(getOrbitTrapAppearance(current)) } }));
  return <>
    <div className="control-panel__grid"><DensityControl config={config} onChange={onChange} /><RangeControl label="Trap response" value={config.material.parameters.trapScale ?? 1} min={0.2} max={3} step={0.05} onChange={(trapScale) => onChange((current) => ({ ...current, material: { ...current.material, parameters: { ...current.material.parameters, trapScale } } }))} /></div>
    <section className="discover-panel__workflow-card"><div className="control-panel__section-heading"><div><p className="control-panel__label">Trap field</p><strong>Compose up to two transformed SDF traps</strong></div><button type="button" disabled={trapSet.traps.length >= MAX_ORBIT_TRAPS} onClick={() => updateTraps((current) => ({ ...cloneOrbitTrapSet(current), traps: [...current.traps, createOrbitTrap('point')] }))}>Add trap</button></div><label><span>Composition</span><select value={trapSet.composition} onChange={(event) => updateTraps((current) => ({ ...cloneOrbitTrapSet(current), composition: event.target.value === 'maximum' ? 'maximum' : 'minimum' }))}><option value="minimum">Nearest / union</option><option value="maximum">Intersection</option></select></label>{trapSet.traps.map((trap, index) => <div className="control-panel__note" key={`trap-${index}`}><div className="control-panel__section-heading"><strong>Trap {index + 1}</strong><button type="button" disabled={trapSet.traps.length === 1} onClick={() => updateTraps((current) => ({ ...cloneOrbitTrapSet(current), traps: current.traps.filter((_, trapIndex) => trapIndex !== index) }))}>Remove</button></div><div className="control-panel__grid"><label><span>Trap {index + 1} shape</span><select value={trap.shape} onChange={(event) => updateTrap(updateTraps, index, { shape: event.target.value as OrbitTrapShape })}>{trapShapes.map((shape) => <option key={shape.id} value={shape.id}>{shape.label}</option>)}</select></label><RangeControl label={`Trap ${index + 1} X`} value={trap.x} min={-2} max={2} step={0.02} onChange={(x) => updateTrap(updateTraps, index, { x })} /><RangeControl label={`Trap ${index + 1} Y`} value={trap.y} min={-2} max={2} step={0.02} onChange={(y) => updateTrap(updateTraps, index, { y })} /><RangeControl label={`Trap ${index + 1} rotation`} value={trap.rotation} min={-3.14} max={3.14} step={0.05} onChange={(rotation) => updateTrap(updateTraps, index, { rotation })} /><RangeControl label={`Trap ${index + 1} scale`} value={trap.scale} min={0.1} max={2} step={0.05} onChange={(scale) => updateTrap(updateTraps, index, { scale })} /></div></div>)}</section>
    <section className="discover-panel__workflow-card"><div className="control-panel__section-heading"><div><p className="control-panel__label">Material response</p><strong>Keep the escape boundary readable while shaping the trap signal</strong></div></div><div className="control-panel__grid"><label><span>Orbit metric</span><select value={appearance.metric} onChange={(event) => updateAppearance((current) => ({ ...cloneOrbitTrapAppearance(current), metric: event.target.value === 'final' ? 'final' : 'nearest' }))}><option value="nearest">Closest approach</option><option value="final">Final orbit point</option></select></label><label><span>Palette mapping</span><select value={appearance.paletteMapping} onChange={(event) => updateAppearance((current) => ({ ...cloneOrbitTrapAppearance(current), paletteMapping: event.target.value as OrbitTrapPaletteMapping }))}><option value="signal">Proximity signal</option><option value="distanceBands">Distance bands</option></select></label><RangeControl label="Exterior trap mix" value={appearance.exteriorMix} min={0} max={1} step={0.05} suffix="%" display={(value) => String(Math.round(value * 100))} onChange={(exteriorMix) => updateAppearance((current) => ({ ...cloneOrbitTrapAppearance(current), exteriorMix }))} /><RangeControl label="Interior trap mix" value={appearance.interiorMix} min={0} max={1} step={0.05} suffix="%" display={(value) => String(Math.round(value * 100))} onChange={(interiorMix) => updateAppearance((current) => ({ ...cloneOrbitTrapAppearance(current), interiorMix }))} /><RangeControl label="Emissive accent" value={appearance.emission} min={0} max={0.7} step={0.05} suffix="%" display={(value) => String(Math.round(value * 100))} onChange={(emission) => updateAppearance((current) => ({ ...cloneOrbitTrapAppearance(current), emission }))} /></div></section>
  </>;
}
function updateParameters(onChange: MaterialControlsProps['onChange'], parameters: Record<string, number>) { onChange((current) => ({ ...current, material: { ...current.material, parameters: { ...current.material.parameters, ...parameters } } })); }
function TopographicMaterialControls({ config, onChange }: Omit<MaterialControlsProps, 'definition'>) { const p = config.material.parameters; return <div className="control-panel__grid"><DensityControl config={config} onChange={onChange} /><RangeControl label="Contour levels" value={p.contourLevels ?? 18} min={2} max={48} step={1} display={(value) => String(Math.round(value))} onChange={(contourLevels) => updateParameters(onChange, { contourLevels })} /><RangeControl label="Contour width" value={p.contourWidth ?? 0.13} min={0.03} max={0.35} step={0.01} onChange={(contourWidth) => updateParameters(onChange, { contourWidth })} /><RangeControl label="Terrain relief" value={p.relief ?? 0.72} min={0} max={1} step={0.05} suffix="%" display={(value) => String(Math.round(value * 100))} onChange={(relief) => updateParameters(onChange, { relief })} /></div>; }
function DomainMaterialControls({ config, onChange }: Omit<MaterialControlsProps, 'definition'>) { const p = config.material.parameters; return <div className="control-panel__grid"><RangeControl label="Phase rotation" value={p.phaseScale ?? 1} min={0.2} max={3} step={0.05} onChange={(phaseScale) => updateParameters(onChange, { phaseScale })} /><RangeControl label="Magnitude ripples" value={p.magnitudeScale ?? 0.38} min={0} max={1.2} step={0.02} onChange={(magnitudeScale) => updateParameters(onChange, { magnitudeScale })} /></div>; }
function SurfaceMaterialControls({ config, onChange }: Omit<MaterialControlsProps, 'definition'>) { const p = config.material.parameters; return <div className="control-panel__grid"><DensityControl config={config} onChange={onChange} /><RangeControl label="Height relief" value={p.height ?? 3.4} min={0.4} max={6} step={0.1} onChange={(height) => updateParameters(onChange, { height })} /><RangeControl label="Light direction" value={p.lightAngle ?? 0.7} min={-3.14} max={3.14} step={0.05} onChange={(lightAngle) => updateParameters(onChange, { lightAngle })} /><RangeControl label="Specular highlight" value={p.specular ?? 0.32} min={0} max={1} step={0.05} suffix="%" display={(value) => String(Math.round(value * 100))} onChange={(specular) => updateParameters(onChange, { specular })} /><RangeControl label="Surface roughness" value={p.roughness ?? 0.55} min={0.05} max={1} step={0.05} suffix="%" display={(value) => String(Math.round(value * 100))} onChange={(roughness) => updateParameters(onChange, { roughness })} /><RangeControl label="Ambient light" value={p.ambient ?? 0.28} min={0} max={1} step={0.05} suffix="%" display={(value) => String(Math.round(value * 100))} onChange={(ambient) => updateParameters(onChange, { ambient })} /></div>; }
function DensityControl({ config, onChange }: Omit<MaterialControlsProps, 'definition'>) { return <RangeControl label="Colour density" value={config.material.parameters.density ?? 0.032} min={0.004} max={0.08} step={0.002} display={(value) => value.toFixed(3)} onChange={(density) => onChange((current) => ({ ...current, material: { ...current.material, parameters: { ...current.material.parameters, density } } }))} />; }
function updateTrap(updateTraps: (updater: (current: ReturnType<typeof getOrbitTrapSet>) => ReturnType<typeof getOrbitTrapSet>) => void, index: number, updates: Partial<ReturnType<typeof getOrbitTrapSet>['traps'][number]>) { updateTraps((current) => ({ ...cloneOrbitTrapSet(current), traps: current.traps.map((trap, trapIndex) => trapIndex === index ? { ...trap, ...updates } : trap) })); }
export function RangeControl({ label, value, min, max, step, suffix = '', display = (next: number) => next.toFixed(2), onChange }: { label: string; value: number; min: number; max: number; step: number; suffix?: string; display?: (value: number) => string; onChange: (value: number) => void }) { return <label><span>{label}</span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /><strong>{display(value)}{suffix}</strong></label>; }
